In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [4]:
df = pd.read_csv('C://temp/stikstof.csv')

In [5]:
df_c = df

In [6]:
df_c.head()

,user_id,status_id,created_at,screen_name,text,source,display_text_width,reply_to_status_id,reply_to_user_id,reply_to_screen_name,...,statuses_count,favourites_count,account_created_at,verified,profile_url,profile_expanded_url,account_lang,profile_banner_url,profile_background_url,profile_image_url
0,x192292190,x1190706087386853382,2019-11-02 19:03:48,jrbonte,Ik zie hier een nieuwe markt voor #boeren die ...,Twitter for Android,235,NaN,NaN,NaN,...,15329,1940,2010-09-18 18:31:19,False,NaN,NaN,NaN,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1046067607...
1,x192292190,x1189458555960778752,2019-10-30 08:26:33,jrbonte,#PFAS #stikstofcrisis #stikstof #grondinverzet...,Twitter for Android,46,NaN,NaN,NaN,...,15329,1940,2010-09-18 18:31:19,False,NaN,NaN,NaN,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1046067607...
2,x192292190,x1189896429449424897,2019-10-31 13:26:30,jrbonte,"@EWdeVlieger @LavieJanRoos ""Dankzij kunstmest ...",Twitter for Android,148,x1189887887376039942,x435167929,EWdeVlieger,...,15329,1940,2010-09-18 18:31:19,False,NaN,NaN,NaN,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1046067607...
3,x192292190,x1189453732024598528,2019-10-30 08:07:23,jrbonte,"""Uit wetenschappelijk onderzoek blijkt dat een...",Twitter for Android,230,NaN,NaN,NaN,...,15329,1940,2010-09-18 18:31:19,False,NaN,NaN,NaN,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1046067607...
4,x192292190,x1189487617605287938,2019-10-30 10:22:02,jrbonte,Naar alle waarschijnlijkheid gaat #Rutte de Po...,Twitter for Android,279,NaN,NaN,NaN,...,15329,1940,2010-09-18 18:31:19,False,NaN,NaN,NaN,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1046067607...

In [22]:
columns = []

for colum in df_c.columns:
    columns.append(colum)

columns = pd.DataFrame(columns)

In [29]:
df_c.describe()

,display_text_width,favorite_count,retweet_count,quote_count,reply_count,symbols,ext_media_type,quoted_favorite_count,quoted_retweet_count,quoted_followers_count,...,retweet_statuses_count,retweet_location,retweet_description,retweet_verified,followers_count,friends_count,listed_count,statuses_count,favourites_count,account_lang
count,9469.000000,9469.000000,9469.000000,0.0,0.0,0.0,0.0,1063.000000,1063.000000,1.063000e+03,...,0.0,0.0,0.0,0.0,9.469000e+03,9469.000000,9469.000000,9469.000000,9469.000000,0.0
mean,170.250290,6.582216,3.156933,NaN,NaN,NaN,NaN,603.395108,173.066792,2.511155e+05,...,NaN,NaN,NaN,NaN,4.245204e+03,991.066005,52.722146,25759.748548,9952.217341,NaN
std,78.798875,49.800787,21.566285,NaN,NaN,NaN,NaN,13516.845103,2714.308175,2.726361e+06,...,NaN,NaN,NaN,NaN,3.508093e+04,1990.283073,222.963231,53366.150780,21648.868711,NaN
min,8.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000e+00,...,NaN,NaN,NaN,NaN,0.000000e+00,0.000000,0.000000,1.000000,0.000000,NaN
25%,103.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,7.000000,4.000000,1.291000e+03,...,NaN,NaN,NaN,NaN,1.180000e+02,155.000000,1.000000,1945.000000,358.000000,NaN
50%,168.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,35.000000,21.000000,5.084000e+03,...,NaN,NaN,NaN,NaN,4.540000e+02,444.000000,6.000000,7629.000000,1986.000000,NaN
75%,248.000000,2.000000,1.000000,NaN,NaN,NaN,NaN,148.000000,77.000000,4.419400e+04,...,NaN,NaN,NaN,NaN,1.384000e+03,1109.000000,32.000000,24128.000000,9580.000000,NaN
max,303.000000,1738.000000,733.000000,NaN,NaN,NaN,NaN,439838.000000,87553.000000,6.647671e+07,...,NaN,NaN,NaN,NaN,1.094918e+06,49629.000000,4390.000000,652508.000000,346043.000000,NaN

In [31]:
df_c.columns

Index(['user_id', 'status_id', 'created_at', 'screen_name', 'text', 'source',
       'display_text_width', 'reply_to_status_id', 'reply_to_user_id',
       'reply_to_screen_name', 'is_quote', 'is_retweet', 'favorite_count',
       'retweet_count', 'quote_count', 'reply_count', 'hashtags', 'symbols',
       'urls_url', 'urls_t.co', 'urls_expanded_url', 'media_url', 'media_t.co',
       'media_expanded_url', 'media_type', 'ext_media_url', 'ext_media_t.co',
       'ext_media_expanded_url', 'ext_media_type', 'mentions_user_id',
       'mentions_screen_name', 'lang', 'quoted_status_id', 'quoted_text',
       'quoted_created_at', 'quoted_source', 'quoted_favorite_count',
       'quoted_retweet_count', 'quoted_user_id', 'quoted_screen_name',
       'quoted_name', 'quoted_followers_count', 'quoted_friends_count',
       'quoted_statuses_count', 'quoted_location', 'quoted_description',
       'quoted_verified', 'retweet_status_id', 'retweet_text',
       'retweet_created_at', 'retweet_source', 'retweet_favorite_count',
       'retweet_retweet_count', 'retweet_user_id', 'retweet_screen_name',
       'retweet_name', 'retweet_followers_count', 'retweet_friends_count',
       'retweet_statuses_count', 'retweet_location', 'retweet_description',
       'retweet_verified', 'place_url', 'place_name', 'place_full_name',
       'place_type', 'country', 'country_code', 'geo_coords', 'coords_coords',
       'bbox_coords', 'status_url', 'name', 'location', 'description', 'url',
       'protected', 'followers_count', 'friends_count', 'listed_count',
       'statuses_count', 'favourites_count', 'account_created_at', 'verified',
       'profile_url', 'profile_expanded_url', 'account_lang',
       'profile_banner_url', 'profile_background_url', 'profile_image_url'],
      dtype='object')

In [27]:
def resumetable(df):
    print(f"Dataset Shape: {df.shape}")
    summary = pd.DataFrame(df.dtypes,columns=['dtypes'])
    summary = summary.reset_index()
    summary['Name'] = summary['index']
    summary = summary[['Name','dtypes']]
    summary['Missing'] = df.isnull().sum().values    
    summary['Uniques'] = df.nunique().values
    return summary

resumetable(df_c)

Dataset Shape: (9469, 90)

                      Name   dtypes  Missing  Uniques
0                  user_id   object        0     5328
1                status_id   object        0     9469
2               created_at   object        0     9347
3              screen_name   object        0     5328
4                     text   object        0     9464
5                   source   object        0       97
6       display_text_width    int64        0      287
7       reply_to_status_id   object     5410     3180
8         reply_to_user_id   object     5269     1929
9     reply_to_screen_name   object     5269     1930
10                is_quote     bool        0        2
11              is_retweet     bool        0        1
12          favorite_count    int64        0      175
13           retweet_count    int64        0      128
14             quote_count  float64     9469        0
15             reply_count  float64     9469        0
16                hashtags   object     5828     2500
17                 symbols  float64     9469        0
18                urls_url   object     5546     2059
19               urls_t.co   object     5546     3801
20       urls_expanded_url   object     5546     2632
21               media_url   object     8377     1082
22              media_t.co   object     8377     1091
23      media_expanded_url   object     8377     1082
24              media_type   object     8377        2
25           ext_media_url   object     8377     1082
26          ext_media_t.co   object     8377     1091
27  ext_media_expanded_url   object     8377     1082
28          ext_media_type  float64     9469        0
29        mentions_user_id   object     4097     3306
..                     ...      ...      ...      ...
60     retweet_description  float64     9469        0
61        retweet_verified  float64     9469        0
62               place_url   object     9123      163
63              place_name   object     9123      163
64         place_full_name   object     9123      163
65              place_type   object     9123        5
66                 country   object     9124        8
67            country_code   object     9124        8
68              geo_coords   object        0        1
69           coords_coords   object        0        1
70             bbox_coords   object        0      164
71              status_url   object        0     9469
72                    name   object        0     5211
73                location   object     3075     1839
74             description   object     1348     4480
75                     url   object     6000     1946
76               protected     bool        0        1
77         followers_count    int64        0     2060
78           friends_count    int64        0     1856
79            listed_count    int64        0      356
80          statuses_count    int64        0     4493
81        favourites_count    int64        0     3436
82      account_created_at   object        0     5328
83                verified     bool        0        2
84             profile_url   object     6000     1946
85    profile_expanded_url   object     6008     1911
86            account_lang  float64     9469        0
87      profile_banner_url   object     2594     3827
88  profile_background_url   object     2146       20
89       profile_image_url   object        0     5114

[90 rows x 4 columns]

In [28]:
def check_missing_data(df):
 
    # check for any missing data in the df (display in descending order)
 
    return df.isnull().sum().sort_values(ascending=False)

check_missing_data(df_c)

retweet_retweet_count      9469
reply_count                9469
retweet_verified           9469
retweet_description        9469
retweet_location           9469
retweet_statuses_count     9469
retweet_friends_count      9469
retweet_followers_count    9469
retweet_name               9469
retweet_user_id            9469
retweet_screen_name        9469
retweet_favorite_count     9469
retweet_source             9469
retweet_created_at         9469
retweet_text               9469
retweet_status_id          9469
quote_count                9469
ext_media_type             9469
account_lang               9469
symbols                    9469
country_code               9124
country                    9124
place_name                 9123
place_url                  9123
place_type                 9123
place_full_name            9123
quoted_location            8619
quoted_description         8444
quoted_screen_name         8406
quoted_user_id             8406
                           ...
location                   3075
profile_banner_url         2594
profile_background_url     2146
description                1348
is_retweet                    0
is_quote                      0
favorite_count                0
display_text_width            0
source                        0
text                          0
screen_name                   0
created_at                    0
status_id                     0
retweet_count                 0
profile_image_url             0
lang                          0
geo_coords                    0
coords_coords                 0
bbox_coords                   0
status_url                    0
name                          0
protected                     0
followers_count               0
friends_count                 0
listed_count                  0
statuses_count                0
favourites_count              0
account_created_at            0
verified                      0
user_id                       0
Length: 90, dtype: int64

#### Lets look at the basic stats for now

In [36]:
#amount of tweets in the data set coontaining "stikstof"
df_c.shape[0]

9469

In [43]:
# The amount of unique users whoo have tweeted aboout the subject
df_c['screen_name'].nunique()

5328

In [55]:
# Date range of the data set
print(df_c['created_at'].min())
print(df_c['created_at'].max())

min_date = df_c['created_at'].min()
min_date = pd.to_datetime(min_date[:10])
max_date = df_c['created_at'].max()
max_date = pd.to_datetime(max_date[:10])

no_days = max_date - min_date

print(no_days)

2019-10-24 15:17:08
2019-11-02 19:03:48
9 days 00:00:00

In [78]:
# avg num of tweets per user

df_c["counter"] = 1

A = df_c.groupby('screen_name')['counter'].sum().reset_index()
A['counter'].mean()

1.7772147147147148

In [127]:
### Most used hashtags
HASH = df_c['hashtags'].dropna().reset_index()

HASH= df_c['hashtags'].dropna().str.split()

ModuleNotFoundError: No module named 'obo'

In [128]:
def tokenize():
    if HASH is not None:
        words = HASH.lower().split()
        return words
    else:
        return None


def count_word(tokens, token):
    count = 0

    for element in tokens:
        # Remove Punctuation
        word = element.replace(",","")
        word = word.replace(".","")

        # Found Word?
        if word == token:
            count += 1
    return count
    
    
# Tokenize the Book
HASH = tokenize()

# Get Word Count
word = 'day'
frequency = count_word(words, word)
print('Word: [' + word + '] Frequency: ' + str(frequency))

AttributeError: 'Series' object has no attribute 'lower'

<3641x2495 sparse matrix of type '<class 'numpy.int64'>'
	with 11850 stored elements in Compressed Sparse Row format>

,0,1,2,3,4,5,6,7,8,9,...,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3611,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3612,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3613,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3615,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3616,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3617,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3618,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3619,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3620,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3621,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3622,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3623,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3629,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3631,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3633,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3634,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3635,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3636,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3637,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3640,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0